# fly.toml app configuration file generated for seat-reservation-system-api on 2025-08-14T21:55:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'seat-reservation-system-api'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
